# These are supported funding model platforms

github: dolfly # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2] ['dolfly']
patreon: dolfly # Replace with a single Patreon username
open_collective: dolfly # Replace with a single Open Collective username
ko_fi: dolfly # Replace with a single Ko-fi username
tidelift:  # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: autoproxy # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: dolfly # Replace with a single Liberapay username
issuehunt: dolfly # Replace with a single IssueHunt username
otechie: dolfly # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
